/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Subject;

import Class.ClassManagement;
import Counting.Thongke;
import LoginForAdmin.Login;
import Student.StudentManagement;

/**
 *
 * @author admin
 */
public class SubjectManagement extends javax.swing.JFrame {

    /**
     * Creates new form SubjectManagement
     */
    public SubjectManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        stumana = new javax.swing.JButton();
        subjectmana = new javax.swing.JButton();
        classmana = new javax.swing.JButton();
        counting = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        inputtext = new javax.swing.JTextField();
        searching = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        addsub = new javax.swing.JButton();
        changesub = new javax.swing.JButton();
        delsub = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("QUẢN LÝ MÔN HỌC");

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Đăng xuất");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        stumana.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        stumana.setText("Quản lý thông tin sinh viên");
        stumana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stumanaMouseClicked(evt);
            }
        });

        subjectmana.setBackground(new java.awt.Color(0, 153, 255));
        subjectmana.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        subjectmana.setForeground(new java.awt.Color(255, 255, 255));
        subjectmana.setText("Quản lý môn học");

        classmana.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        classmana.setText("Quản lý lớp học");
        classmana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                classmanaMouseClicked(evt);
            }
        });
        classmana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classmanaActionPerformed(evt);
            }
        });

        counting.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        counting.setText("Thống kê");
        counting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                countingMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel2.setText("Tìm kiếm");

        searching.setBackground(new java.awt.Color(204, 204, 204));
        searching.setText("Tìm kiếm");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã môn học", "Tên môn học", "Số TC", "Khoa", "Mô tả"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(75);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(25);
        }

        addsub.setBackground(new java.awt.Color(204, 204, 204));
        addsub.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addsub.setText("Thêm môn học");
        addsub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addsubMouseClicked(evt);
            }
        });

        changesub.setBackground(new java.awt.Color(204, 204, 204));
        changesub.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        changesub.setText("Sửa thông tin");
        changesub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changesubMouseClicked(evt);
            }
        });

        delsub.setBackground(new java.awt.Color(204, 204, 204));
        delsub.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        delsub.setText("Xóa môn học");
        delsub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delsubMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(stumana)
                .addGap(18, 18, 18)
                .addComponent(subjectmana)
                .addGap(18, 18, 18)
                .addComponent(classmana)
                .addGap(18, 18, 18)
                .addComponent(counting)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jLabel2)
                                .addGap(39, 39, 39)
                                .addComponent(inputtext, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searching))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(addsub)
                                        .addGap(37, 37, 37)
                                        .addComponent(changesub)
                                        .addGap(37, 37, 37)
                                        .addComponent(delsub)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stumana)
                    .addComponent(subjectmana)
                    .addComponent(classmana)
                    .addComponent(counting))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searching))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delsub)
                    .addComponent(changesub)
                    .addComponent(addsub))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void classmanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classmanaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classmanaActionPerformed

    private void stumanaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stumanaMouseClicked
        // TODO add your handling code here:
        StudentManagement sm = new StudentManagement();
        sm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_stumanaMouseClicked

    private void addsubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addsubMouseClicked
        // TODO add your handling code here:
        addSub as = new addSub();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addsubMouseClicked

    private void changesubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changesubMouseClicked
        // TODO add your handling code here:
        changeSub cs = new changeSub();
        cs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_changesubMouseClicked

    private void delsubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delsubMouseClicked
        // TODO add your handling code here:
        delSub ds = new delSub();
        ds.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_delsubMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Login lg = new Login();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void classmanaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_classmanaMouseClicked
        // TODO add your handling code here:
        ClassManagement cm = new ClassManagement();
        cm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_classmanaMouseClicked

    private void countingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_countingMouseClicked
        // TODO add your handling code here:
        Thongke tk = new Thongke();
        tk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_countingMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubjectManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubjectManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubjectManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubjectManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubjectManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addsub;
    private javax.swing.JButton changesub;
    private javax.swing.JButton classmana;
    private javax.swing.JButton counting;
    private javax.swing.JButton delsub;
    private javax.swing.JTextField inputtext;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton searching;
    private javax.swing.JButton stumana;
    private javax.swing.JButton subjectmana;
    // End of variables declaration//GEN-END:variables
}
